CREATE OR REPLACE TRIGGER TRG_CongTonKho
AFTER INSERT ON CHITIETPHIEUNHAP
FOR EACH ROW
BEGIN
    UPDATE BIENTHESANPHAM
    SET SoLuongTon = SoLuongTon + :NEW.SoLuongNhap
    WHERE MaBienThe = :NEW.MaBienThe;
END;