
ALTER TABLE NHANVIEN ADD CONSTRAINT uq_nv_sdt UNIQUE (SDT);
ALTER TABLE NHANVIEN ADD CONSTRAINT chk_nv_sdt CHECK (REGEXP_LIKE(SDT, '^[0-9]{10}$'));
ALTER TABLE NHANVIEN ADD CONSTRAINT chk_nv_trangthai CHECK (TrangThaiLamViec IN ('Dang lam viec', 'Da nghi viec'));

ALTER TABLE TAIKHOAN ADD CONSTRAINT uq_tk_manv UNIQUE (MaNV);
ALTER TABLE TAIKHOAN ADD CONSTRAINT uq_tk_username UNIQUE (UserName);
ALTER TABLE TAIKHOAN ADD CONSTRAINT fk_tk_nv FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV);
ALTER TABLE TAIKHOAN ADD CONSTRAINT chk_tk_trangthai CHECK (TrangThai IN ('Hoat dong', 'Bi khoa'));
ALTER TABLE TAIKHOAN ADD CONSTRAINT chk_tk_vaitro CHECK (VaiTro IN ('Quan ly', 'Nhan vien ban hang', 'Nhan vien kho', 'Nhan vien ke toan'));

ALTER TABLE DANHMUC ADD CONSTRAINT fk_dm_dmcha FOREIGN KEY (MaDMCha) REFERENCES DANHMUC(MaDM);

ALTER TABLE SANPHAM ADD CONSTRAINT fk_sp_dm FOREIGN KEY (MaDM) REFERENCES DANHMUC(MaDM);
ALTER TABLE SANPHAM ADD CONSTRAINT chk_sp_ttkd CHECK (TrangThaiKD IN ('Dang ban', 'Ngung ban'));

ALTER TABLE BIENTHESANPHAM ADD CONSTRAINT fk_bt_sp FOREIGN KEY (MaSP) REFERENCES SANPHAM(MaSP);
ALTER TABLE BIENTHESANPHAM ADD CONSTRAINT chk_bt_giaban CHECK (GiaBan > 0);
ALTER TABLE BIENTHESANPHAM ADD CONSTRAINT chk_bt_tonkho CHECK (SoLuongTon >= 0);

ALTER TABLE NHACUNGCAP ADD CONSTRAINT uq_ncc_sdt UNIQUE (SDT);
ALTER TABLE NHACUNGCAP ADD CONSTRAINT chk_ncc_sdt CHECK (REGEXP_LIKE(SDT, '^[0-9]{10}$'));
ALTER TABLE NHACUNGCAP ADD CONSTRAINT chk_ncc_trangthai CHECK (TrangThaiNCC IN ('Hoat dong', 'Ngung hop tac'));

ALTER TABLE PHIEUNHAP ADD CONSTRAINT fk_pn_ncc FOREIGN KEY (MaNCC) REFERENCES NHACUNGCAP(MaNCC);
ALTER TABLE PHIEUNHAP ADD CONSTRAINT fk_pn_nv FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV);
ALTER TABLE PHIEUNHAP ADD CONSTRAINT chk_pn_giatri CHECK (TongGiaTri >= 0);

ALTER TABLE CHITIETPHIEUNHAP ADD CONSTRAINT pk_ctpn PRIMARY KEY (MaPN, MaBienThe);
ALTER TABLE CHITIETPHIEUNHAP ADD CONSTRAINT fk_ctpn_pn FOREIGN KEY (MaPN) REFERENCES PHIEUNHAP(MaPN);
ALTER TABLE CHITIETPHIEUNHAP ADD CONSTRAINT fk_ctpn_bt FOREIGN KEY (MaBienThe) REFERENCES BIENTHESANPHAM(MaBienThe);
ALTER TABLE CHITIETPHIEUNHAP ADD CONSTRAINT chk_ctpn_sl CHECK (SoLuongNhap > 0);
ALTER TABLE CHITIETPHIEUNHAP ADD CONSTRAINT chk_ctpn_gia CHECK (GiaNhap > 0);

ALTER TABLE PHIEUXUATTRA ADD CONSTRAINT fk_pxt_ncc FOREIGN KEY (MaNCC) REFERENCES NHACUNGCAP(MaNCC);
ALTER TABLE PHIEUXUATTRA ADD CONSTRAINT fk_pxt_nv FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV);

ALTER TABLE CHITIETPHIEUXUATTRA ADD CONSTRAINT pk_ctpxt PRIMARY KEY (MaPhieuTra, MaBienThe);
ALTER TABLE CHITIETPHIEUXUATTRA ADD CONSTRAINT fk_ctpxt_pxt FOREIGN KEY (MaPhieuTra) REFERENCES PHIEUXUATTRA(MaPhieuTra);
ALTER TABLE CHITIETPHIEUXUATTRA ADD CONSTRAINT fk_ctpxt_bt FOREIGN KEY (MaBienThe) REFERENCES BIENTHESANPHAM(MaBienThe);
ALTER TABLE CHITIETPHIEUXUATTRA ADD CONSTRAINT chk_ctpxt_sl CHECK (SoLuong > 0);
ALTER TABLE CHITIETPHIEUXUATTRA ADD CONSTRAINT chk_ctpxt_gia CHECK (GiaXuat >= 0);

ALTER TABLE KHACHHANG ADD CONSTRAINT uq_kh_sdt UNIQUE (SDT);
ALTER TABLE KHACHHANG ADD CONSTRAINT chk_kh_sdt CHECK (REGEXP_LIKE(SDT, '^[0-9]{10}$'));
ALTER TABLE KHACHHANG ADD CONSTRAINT chk_kh_diem CHECK (DiemTichLuy >= 0);

ALTER TABLE KHUYENMAI ADD CONSTRAINT chk_km_ngay CHECK (NgayKetThuc >= NgayBatDau);
ALTER TABLE KHUYENMAI ADD CONSTRAINT chk_km_trangthai CHECK (TrangThaiKM IN ('Dang dien ra', 'Ket thuc'));

ALTER TABLE CHITIETKHUYENMAI ADD CONSTRAINT pk_ctkm PRIMARY KEY (MaKM, MaBienThe);
ALTER TABLE CHITIETKHUYENMAI ADD CONSTRAINT fk_ctkm_km FOREIGN KEY (MaKM) REFERENCES KHUYENMAI(MaKM);
ALTER TABLE CHITIETKHUYENMAI ADD CONSTRAINT fk_ctkm_bt FOREIGN KEY (MaBienThe) REFERENCES BIENTHESANPHAM(MaBienThe);
ALTER TABLE CHITIETKHUYENMAI ADD CONSTRAINT chk_ctkm_gia CHECK (GiaKhuyenMai > 0);

ALTER TABLE DONHANG ADD CONSTRAINT fk_dh_kh FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH);
ALTER TABLE DONHANG ADD CONSTRAINT fk_dh_km FOREIGN KEY (MaKM) REFERENCES KHUYENMAI(MaKM);
ALTER TABLE DONHANG ADD CONSTRAINT fk_dh_nv FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV);
ALTER TABLE DONHANG ADD CONSTRAINT chk_dh_tongtien CHECK (TongTienDH >= 0);
ALTER TABLE DONHANG ADD CONSTRAINT chk_dh_diemsd CHECK (DiemSuDung >= 0);
ALTER TABLE DONHANG ADD CONSTRAINT chk_dh_diemnhan CHECK (DiemNhanDuoc >= 0);

ALTER TABLE CHITIETDONHANG ADD CONSTRAINT pk_ctdh PRIMARY KEY (MaDH, MaBienThe);
ALTER TABLE CHITIETDONHANG ADD CONSTRAINT fk_ctdh_dh FOREIGN KEY (MaDH) REFERENCES DONHANG(MaDH);
ALTER TABLE CHITIETDONHANG ADD CONSTRAINT fk_ctdh_bt FOREIGN KEY (MaBienThe) REFERENCES BIENTHESANPHAM(MaBienThe);
ALTER TABLE CHITIETDONHANG ADD CONSTRAINT chk_ctdh_sl CHECK (SoLuong > 0);
ALTER TABLE CHITIETDONHANG ADD CONSTRAINT chk_ctdh_gia CHECK (GiaBanLucMua >= 0);

ALTER TABLE HOADON ADD CONSTRAINT uq_hd_madh UNIQUE (MaDH);
ALTER TABLE HOADON ADD CONSTRAINT fk_hd_dh FOREIGN KEY (MaDH) REFERENCES DONHANG(MaDH);
ALTER TABLE HOADON ADD CONSTRAINT fk_hd_nv FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV);
ALTER TABLE HOADON ADD CONSTRAINT chk_hd_tongtien CHECK (TongTienHD >= 0); 
ALTER TABLE HOADON ADD CONSTRAINT chk_hd_pttt CHECK (PhuongThucTT IN ('Tien mat', 'Chuyen khoan'));