CREATE TABLE BIENTHESANPHAM (
    MaBienThe VARCHAR2(20) PRIMARY KEY, 
    MaSP VARCHAR2(20) NOT NULL REFERENCES SANPHAM(MaSP),
    MaQR VARCHAR2(255), 
    MauSac NVARCHAR2(50) NOT NULL,
    KichThuoc VARCHAR2(10) NOT NULL,
    GiaBan NUMBER(15,0) NOT NULL CHECK (GiaBan > 0),
    SoLuongTon NUMBER DEFAULT 0 CHECK (SoLuongTon >= 0)
);