CREATE TABLE CHITIETDONHANG (
    MaDH VARCHAR2(20) REFERENCES DONHANG(MaDH), 
    MaBienThe VARCHAR2(20) REFERENCES BIENTHESANPHAM(MaBienThe), 
    SoLuong NUMBER NOT NULL CHECK (SoLuong > 0), 
    GiaBanLucMua NUMBER(15,0),
    PRIMARY KEY (MaDH, MaBienThe)
);