CREATE TABLE CHITIETPHIEUXUATTRA (
    MaPhieuTra VARCHAR2(10) REFERENCES PHIEUXUATTRA(MaPhieuTra),
    MaBienThe VARCHAR2(20) REFERENCES BIENTHESANPHAM(MaBienThe),
    SoLuong NUMBER(5,0),
    PRIMARY KEY (MaPhieuTra, MaBienThe)
);