CREATE TABLE CHITIETKHUYENMAI (
    MaKM VARCHAR2(20) REFERENCES KHUYENMAI(MaKM),
    MaBienThe VARCHAR2(20) REFERENCES BIENTHESANPHAM(MaBienThe),
    GiaKhuyenMai NUMBER(15,0), 
    PRIMARY KEY (MaKM, MaBienThe)
);