CREATE TABLE CHITIETPHIEUNHAP (
    MaPN VARCHAR2(10) REFERENCES PHIEUNHAP(MaPN),
    MaBienThe VARCHAR2(20) REFERENCES BIENTHESANPHAM(MaBienThe), 
    SoLuongNhap NUMBER(5,0),
    GiaNhap NUMBER(15,0), 
    PRIMARY KEY (MaPN, MaBienThe)
);