CREATE TABLE DONHANG (
    MaDH VARCHAR2(20) PRIMARY KEY,
    NgayMua DATE DEFAULT SYSDATE,
    TongTienDH NUMBER(15,0) NOT NULL,
    MaKH CHAR(5) NOT NULL REFERENCES KHACHHANG(MaKH), 
    MaKM VARCHAR2(20) REFERENCES KHUYENMAI(MaKM),
    DiemSuDung NUMBER DEFAULT 0, 
    DiemNhanDuoc NUMBER DEFAULT 0,
    MaNV VARCHAR2(10) REFERENCES NHANVIEN(MaNV)
);