CREATE TABLE HOADON (
    MaHD VARCHAR2(20) PRIMARY KEY,
    MaDH VARCHAR2(20) NOT NULL UNIQUE REFERENCES DONHANG(MaDH),
    NgayXuat DATE DEFAULT SYSDATE, 
    TongTienHD NUMBER(15,0),
    PhuongThucTT NVARCHAR2(50) CHECK (PhuongThucTT IN ('Tien mat', 'Chuyen khoan')),
    GhiChu NVARCHAR2(255),
    MaNV VARCHAR2(10) REFERENCES NHANVIEN(MaNV)
);