CREATE TABLE PHIEUNHAP (
    MaPN VARCHAR2(10) PRIMARY KEY, 
    NgayNhap DATE, 
    TongGiaTri NUMBER(15,0), 
    MaNCC VARCHAR2(10) REFERENCES NHACUNGCAP(MaNCC),
    MaNV VARCHAR2(10) REFERENCES NHANVIEN(MaNV)
);