CREATE TABLE PHIEUXUATTRA (
    MaPhieuTra VARCHAR2(10) PRIMARY KEY, 
    MaNCC VARCHAR2(10) REFERENCES NHACUNGCAP(MaNCC),
    MaNV VARCHAR2(10) REFERENCES NHANVIEN(MaNV),
    NgayTra DATE, 
    LyDo NVARCHAR2(200) 
);