CREATE TABLE SANPHAM (
    MaSP VARCHAR2(20) PRIMARY KEY,
    MaDM VARCHAR2(20) NOT NULL REFERENCES DANHMUC(MaDM),
    TenSP NVARCHAR2(200) NOT NULL,
    TrangThaiKD VARCHAR2(20) DEFAULT 'Dang ban' CHECK (TrangThaiKD IN ('Dang ban', 'Ngung ban'))
);