CREATE TABLE TAIKHOAN (
    MaTaiKhoan VARCHAR2(10) PRIMARY KEY,
    MaNV VARCHAR2(10) REFERENCES NHANVIEN(MaNV),
    UserName VARCHAR2(30) UNIQUE NOT NULL,
    PassWord VARCHAR2(255) NOT NULL, 
    NgayTao DATE DEFAULT SYSDATE,
    TrangThai NVARCHAR2(20) DEFAULT 'Hoat dong' CHECK (TrangThai IN ('Hoat dong', 'Bi khoa')) 
);