CREATE OR REPLACE TRIGGER TRG_TruKhoKhiXuatTra
AFTER INSERT ON CHITIETPHIEUXUATTRA
FOR EACH ROW
BEGIN
    UPDATE BIENTHESANPHAM
    SET SoLuongTon = SoLuongTon - :NEW.SoLuong
    WHERE MaBienThe = :NEW.MaBienThe;
END;