CREATE TABLE BIENTHESANPHAM (
    MaBienThe VARCHAR2(20) PRIMARY KEY,
    MaSP VARCHAR2(20) NOT NULL,
    MauSac NVARCHAR2(50) NOT NULL,
    KichThuoc VARCHAR2(10) NOT NULL,
    GiaBan NUMBER(15,0) NOT NULL,
    SoLuongTon NUMBER(8,0) DEFAULT 0 NOT NULL
);