CREATE TABLE DONHANG (
    MaDH VARCHAR2(20) PRIMARY KEY,
    NgayMua DATE DEFAULT SYSDATE NOT NULL,
    TongTienDH NUMBER(15,0) NOT NULL,
    MaKH VARCHAR2(10) NOT NULL,
    MaKM VARCHAR2(20),
    DiemSuDung NUMBER(6,0) DEFAULT 0 NOT NULL,
    DiemNhanDuoc NUMBER(6,0) DEFAULT 0 NOT NULL,
    MaNV VARCHAR2(20) NOT NULL
};