CREATE TABLE HOADON (
    MaHD VARCHAR2(20) PRIMARY KEY,
    MaDH VARCHAR2(20) NOT NULL,
    NgayXuat DATE DEFAULT SYSDATE NOT NULL,
    TongTienHD NUMBER(15,0) NOT NULL,
    PhuongThucTT NVARCHAR2(50) NOT NULL,
    GhiChu NVARCHAR2(255),
    MaNV VARCHAR2(20) NOT NULL
};