CREATE TABLE KHUYENMAI (
    MaKM VARCHAR2(20) PRIMARY KEY,
    TenKM NVARCHAR2(100) NOT NULL,
    NgayBatDau DATE NOT NULL,
    NgayKetThuc DATE NOT NULL,
    TrangThaiKM VARCHAR2(20) DEFAULT 'Dang dien ra' NOT NULL
);