CREATE TABLE NHACUNGCAP (
    MaNCC VARCHAR2(20) PRIMARY KEY,
    TenNCC NVARCHAR2(100) NOT NULL,
    SDT VARCHAR2(10) NOT NULL,
    DiaChi NVARCHAR2(200) NOT NULL,
    TrangThaiNCC VARCHAR2(20) DEFAULT 'Hoat dong' NOT NULL
};