CREATE TABLE NHANVIEN (
    MaNV VARCHAR2(20) PRIMARY KEY,
    HoTen NVARCHAR2(50) NOT NULL,
    SDT VARCHAR2(10) NOT NULL,
    ChucVu NVARCHAR2(30) NOT NULL,
    TrangThaiLamViec VARCHAR2(30) DEFAULT 'Dang lam viec' NOT NULL
};