CREATE TABLE PHIEUXUATTRA (
    MaPhieuTra VARCHAR2(10) PRIMARY KEY,
    MaNCC VARCHAR2(20) NOT NULL,
    MaNV VARCHAR2(20) NOT NULL,
    NgayTra DATE DEFAULT SYSDATE NOT NULL,
    LyDo NVARCHAR2(200) NOT NULL
);