CREATE TABLE PHIEUNHAP (
    MaPN VARCHAR2(10) PRIMARY KEY,
    NgayNhap DATE DEFAULT SYSDATE NOT NULL,
    TongGiaTri NUMBER(15,0) DEFAULT 0 NOT NULL,
    MaNCC VARCHAR2(20) NOT NULL,
    MaNV VARCHAR2(20) NOT NULL
};