CREATE TABLE TAIKHOAN (
    MaTaiKhoan VARCHAR2(10) PRIMARY KEY,
    MaNV VARCHAR2(20) NOT NULL,
    UserName VARCHAR2(50) NOT NULL,
    PassWord VARCHAR2(255) NOT NULL,
    NgayTao DATE DEFAULT SYSDATE NOT NULL,
    TrangThai VARCHAR2(30) DEFAULT 'Hoat dong' NOT NULL
};