CREATE OR REPLACE TRIGGER TRG_HoanKho
AFTER DELETE ON CHITIETDONHANG
FOR EACH ROW
BEGIN
    UPDATE BIENTHESANPHAM
    SET SoLuongTon = SoLuongTon + :OLD.SoLuong
    WHERE MaBienThe = :OLD.MaBienThe;
END;