CREATE OR REPLACE TRIGGER TRG_CapNhatKho
AFTER INSERT ON CHITIETDONHANG
FOR EACH ROW
BEGIN
    UPDATE BIENTHESANPHAM
    SET SoLuongTon = SoLuongTon - :NEW.SoLuong
    WHERE MaBienThe = :NEW.MaBienThe;
END;
